---

defaults: &defaults
  docker:
    # Primary image where all commands are run
    - image: canonicalwebteam/dev
      environment:
          SECRET_KEY: development
          DATABASE_URL: postgresql://root@localhost/circle_test
          OS_AUTH_URL: http://localhost:8080/auth/v1.0
          OS_USERNAME: test:tester
          OS_PASSWORD: testing
          OS_AUTH_VERSION: 1.0

    # Service container image
    - image: circleci/postgres:9.6.5-alpine-ram
    - image: bouncestorage/swift-aio:latest

  working_directory: /srv

version: 2
jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint python code
          command: yarn lint-python
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Install requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run migrations
          command: alembic upgrade head
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source=. -m unittest discover tests
            bash <(curl -s https://codecov.io/bash) -cF python
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn
      - run:
          name: Install pip dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost/_status/check
workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python
      - test-site
